{% set name = "lasio" %}
{% set version = "0.31" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kinverarity1/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 140eab1b74b63374bc2d1a96f83143823d3432f84bb32311071c40bb22f59d9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ PKG_VERSION }}
  number: 0
  entry_points:
    - las2excel = lasio.excel:main
    - las2excelbulk = lasio.excel:main_bulk
    - lasversionconvert = lasio.convert_version:convert_version
    - lasio = lasio:version

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - chardet
    - pandas
    - openpyxl

test:
  imports:
    - lasio
  commands:
    - pip list
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kinverarity1/lasio
  summary: 'Read/write well data from Log ASCII Standard (LAS) files'
  description: |
    This is a Python 3.7+ package to read and write Log ASCII Standard (LAS) files, used for borehole data such as geophysical, geological, or petrophysical logs.

    It's compatible with versions 1.2 and 2.0 of the LAS file specification, published by the Canadian Well Logging Society. Support for LAS 3 is being worked on.

    **Note:**
    Maintainers of this recipe are not the authors of the lasio Python package itself.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://lasio.readthedocs.io/en/stable/
  dev_url: https://github.com/kinverarity1/lasio/


extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
